version: '3.7'

services:
  postgresql-primary:
    image: bitnami/postgresql:13
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - postgresql_master_data:/home/postgres/pgdata/data
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    environment:
      - POSTGRESQL_PGAUDIT_LOG=READ,WRITE
      - POSTGRESQL_LOG_HOSTNAME=true
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_user
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=postgres
      - ALLOW_EMPTY_PASSWORD=no
      - POSTGRES_HOST_AUTH_METHOD=trust

  postgresql-replica:
    image: bitnami/postgresql:13
    restart: always
    ports:
      - '5433:5432'
    depends_on:
      - postgresql-primary
    environment:
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_MASTER_HOST=postgresql-primary
      - POSTGRESQL_PGAUDIT_LOG=READ
      - POSTGRESQL_LOG_HOSTNAME=true
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_user
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - ALLOW_EMPTY_PASSWORD=no
      - POSTGRES_HOST_AUTH_METHOD=trust

  pgbouncer:
    image: edoburu/pgbouncer
    restart: always
    ports:
      - '6432:6432'
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=postgresql-primary
      - DB_PORT=5432
      - POOL_MODE=session
      - MAX_CLIENT_CONN=100
      - DEFAULT_POOL_SIZE=20
      - AUTH_TYPE=md5
      - AUTH_FILE=/etc/pgbouncer/users.txt
    volumes:
      - ./pgbouncer/users.txt:/etc/pgbouncer/users.txt

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - '8080:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin

volumes:
  postgresql_master_data:
    driver: local